name: CI - Single Job

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Dar permisos de ejecución al wrapper de Maven
        run: chmod +x mvnw

      - name: Compile code
        run: ./mvnw compile --no-transfer-progress

      - name: Generate test report
        uses: dorny/test-reporter@v1
        with:
          reporter: google-java-format
          fail-on: failed-tests 

      - name: Run unit tests
        run: ./mvnw test --no-transfer-progress 

      - name: Run integration tests
        run: ./mvnw verify --no-transfer-progress

      - name: Upload unit tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: target/surefire-reports/*.xml
          retention-days: 7

      - name: Upload integration tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: target/failsafe-reports/*.xml
          retention-days: 7
