name: CI - Single Job

# Se ejecuta cuando se hace un push o una pull request al repositorio.
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Revisamos el código del repositorio para que el workflow pueda acceder a él.
      - name: Checkout code
        uses: actions/checkout@v4
      # 2. Configuramos el JDK 21 para compilar y ejecutar las pruebas del proyecto Spring Boot Maven.
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      # 3. Dar permisos de ejecución al wrapper de Maven para poder compilar el proyecto y ejecutar las pruebas.
      # X1 | Antes habrá que darle permisos de escritura con chmod.
      - name: Dar permisos de ejecución al wrapper de Maven
        run: chmod +x mvnw

      # 4. Compile el proyecto Spring Boot Maven proporcionado. (./mvnw compile --no-transfer-progress)
      - name: Compile code
        run: ./mvnw compile --no-transfer-progress

      # 5. Ejecute los tests unitarios (./mvnw test --no-transfer-progress)
      - name: Run unit tests
        run: ./mvnw test --no-transfer-progress
        continue-on-error: true

      # 6. Ejecute los tests de integración (./mvnw verify --no-transfer-progress) | X1
      - name: Run integration tests
        run: ./mvnw verify --no-transfer-progress
        continue-on-error: true

      # 7. Convertir XML a JSON para que github-test-reporter lo entienda
      - name: Convert Surefire & Failsafe to CTRF JSON
        if: always()
        run: |
          npx junit-to-ctrf target/surefire-reports/TEST-*.xml -o ctrf/surefire-report.json
          npx junit-to-ctrf target/failsafe-reports/TEST-*.xml -o ctrf/failsafe-report.json

      # 8. Genere un informe de resultados. Para ello puedes tener en cuenta el workflow disponible de GitHub-test-reporter.
      - name: Generación de informe de resultados(github-test-reporter)
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: './ctrf/*.json'
          github-report: true
        if: always()

      # Inclusión sergio - 9. Publicar el informe en la pestaña "Checks"
      - name: Reporte de Pruebas (dorny)
        uses: dorny/test-reporter@v1
        if: success() || failure() # Ejecuta este paso aunque los tests fallen
        with:
          name: Resultados de Pruebas Maven
          path: 'target/*-reports/TEST-*.xml' # Lee la carpeta surefire y failsafe
          reporter: java-junit

      #  Inclusión sergio - 10. Subir los XML como artefacto descargable (retención de 7 días)
      - name: Subir reportes XML de tests
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-reports-xml
          path: 'target/*-reports/TEST-*.xml'
          retention-days: 7

      # 11. Generador del badge de cobertura de Jacoco
      - name: Generate Jacoco Badge
        uses: cicirello/jacoco-badge-generator@v2
        if : always()
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv

      # 12. Hacer commit de los badges de Jacoco para que se muestren en el README
      - name: Commit and push badges
        if: ${{ always() && github.event_name == 'push' }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .github/badges/
          git commit -m "Autogenerated JaCoCo coverage badges" || echo "No changes to commit"
          git push

      # 13. Subir los informes de pruebas unitarias e integración como artefactos para su posterior análisis.
      - name: Upload unit tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: target/surefire-reports/*.xml
          retention-days: 7
      # 14. Subir los informes de pruebas de integración como artefactos para su posterior análisis.
      - name: Upload integration tests report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: target/failsafe-reports/*.xml
          retention-days: 7
